# Generated by Django 5.0.7 on 2024-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=50, null=True, verbose_name='Curso'),
        ),
    ]
