# Generated by Django 5.0.7 on 2024-07-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=50, verbose_name='Curso'),
        ),
    ]
